apiVersion: apps/v1

kind: Deployment

metadata:
  name: grafana
  labels:
    app: grafana

spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    
    spec:
      containers:
        - name: grafana
          image: ashucybertron/grafana:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always 
