apiVersion: apps/v1

kind: Deployment

metadata:
  name: prom-deploy
  labels:
    app: prometheus

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prom-deploy
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prom-pv-vol
          persistentVolumeClaim:
            claimName: prom-pv-volclaim
        
      containers:
        - name: prometheus
          image: ashucybertron/prometheus:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: "/metrics"
              name: prom-pv-vol
              
