apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: prom-pv-volclaim

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi